const WineList = {
  Neirano: {
    varietal: 'Prosecco',
    grapes: ['Glera'],
    vintage: 'NV',
    appellation: 'Veneto, Italy',
    tastingNotes: [
      'White flowers',
      'Crisp',
      'Apple',
      'Charmat Method',
    ],
    type: 'bubbly',
    techSheet: require('../../assets/TechSheets/Nov2017/Neirano.pdf'),
  },
  Valor: {
    varietal: 'Cava',
    grapes: ['Xarel-lo', 'Macabeo', 'Parellada'],
    vintage: 'NV',
    appellation: 'Penedes, Spain',
    tastingNotes: [
      'Brioche',
      'Hazelnut',
      'Very dry',
      'Creamy',
    ],
    type: 'bubbly',
    techSheet: {},
  },
  Mercat: {
    varietal: 'Sparkling Rose',
    grapes: ['Xarel-lo', 'Macabeo,', 'Parellada', 'Monastrell, 5%'],
    vintage: 'NV',
    appellation: 'Penedes, Spain',
    tastingNotes: [
      'Pink grapefruit',
      'Wild strawberry',
      'Crushed raspberry',
      'Fine bubbles',
    ],
    type: 'bubbly',
    techSheet: {},
  },
  'Ca del Sarto': {
    varietal: 'Pinot Grigio',
    grapes: ['Pinot Grigio'],
    vintage: 2016,
    appellation: 'Friuli, Italy',
    tastingNotes: [
      'Lemon',
      'Lime',
      'Fig',
      'Smooth texture',
    ],
    type: 'white',
    techSheet: {},
  },
  Fruitiere: {
    varietal: 'Melon',
    grapes: ['Melon de Bourgogne', 'Chardonnay', 'Sauvignon Blanc'],
    vintage: 2016,
    appellation: 'Loire Valley, France',
    tastingNotes: [
      'White grapefruit',
      'Wet rock',
      'Sea-spray',
      'Musky',
    ],
    type: 'white',
    techSheet: {},
  },
  Oniric: {
    varietal: 'Xarel-lo',
    grapes: ['Xarel-lo'],
    vintage: 2016,
    appellation: 'Rias Baixas, Spain',
    tastingNotes: [
      'Golden delicious',
      'Lemon pith',
      'White flowers',
      'Green almond',
    ],
    type: 'white',
    techSheet: {},
  },
  'Last August': {
    varietal: 'Sauvignon Blanc',
    grapes: ['Sauvignon Blanc'],
    vintage: 2016,
    appellation: 'Lake County, California',
    tastingNotes: [
      'Lime zest',
      'Green papaya',
      'Grassy',
      'Racy acidity',
    ],
    type: 'white',
    techSheet: {},
  },
  Terra: {
    varietal: 'Vermentino, Chardonnay',
    grapes: ['Vermentino, 60%', 'Chardonnay, 40%'],
    vintage: 2016,
    appellation: 'Corsica, France',
    tastingNotes: [
      'Acacia blossom',
      'Tame minerality',
      'Dried herbs',
      'White peach',
    ],
    type: 'white',
    techSheet: {},
  } ,
  Perfekt: {
    varietal: 'Riesling',
    grapes: ['Riesling'],
    vintage: 2015,
    appellation: 'Mosel, Germany',
    tastingNotes: [
      'Floral notes',
      'White peach',
      'Juicy',
      'Off-dry',
    ],
    type: 'white',
    techSheet: {},
  },
  Scarpetta: {
    varietal: 'Friulano-Chardonnay',
    grapes: ['Chardonnay, 80%', 'Friulano, 20%'],
    vintage: 2015,
    appellation: 'Italy',
    tastingNotes: [
      'Fuji apple',
      'Lemon rind',
      'Grapefruit peel',
      'Dried honey',
    ],
    type: 'white',
    techSheet: {},
  },
  Frame: {
    varietal: 'Chardonnay',
    grapes: ['Chardonnay'],
    vintage: 2016,
    appellation: 'California',
    tastingNotes: [
      'Golden apple',
      'Crushed granite',
      'Lime blossom',
      'Orange marmalade',
    ],
    type: 'white',
    techSheet: {},
  },
  Curator: {
    varietal: 'Chenin Blanc',
    grapes: ['Chenin Blanc, 60%', 'Chardonnay, 20%', 'Viognier, 20%'],
    vintage: 2016,
    appellation: 'South Africa',
    tastingNotes: [
      'Apricot',
      'Dried peach',
      'Exotic spice',
      'Beeswax'
    ],
    type: 'white',
    techSheet: {},
  },
  'Holly\'s Way': {
    varietal: 'Chardonnay',
    grapes: ['Chardonnay'],
    vintage: 2016,
    appellation: 'California',
    tastingNotes: [
      'Asian pear',
      'Meyer lemon',
      'Tahitian vanilla',
      'Subtle toast',
    ],
    type: 'white',
    techSheet: {},
  },
  'Ca del Re': {
    varietal: 'Moscato D\'Asti',
    grapes: ['Moscato'],
    vintage: 2016,
    appellation: 'Asti, Italy',
    tastingNotes: [
      'Exotic flowers',
      'Pineapple',
      'Peaches',
      'Citrus',
    ],
    type: 'white',
    techSheet: {},
  },
  'L\'Excellence': {
    varietal: 'rose',
    grapes: ['Grenache, 40%', 'Cinsault, 40%', 'Syrah, 20%'],
    vintage: 2016,
    appellation: 'St. Chinian, France',
    tastingNotes: [
      'Strawberry',
      'Pink grapefruit',
      'White pepper',
      'Fresh herbs',
    ],
    type: 'rose',
    techSheet: {},
  },
  Stagedive: {
    varietal: 'Pinot Noir',
    grapes: ['Pinot Noir'],
    vintage: 2016,
    appellation: 'California',
    tastingNotes: [
      'Pomegranate',
      'Red plum',
      'Subtle wood spice',
      'Forest floor',
    ],
    type: 'red',
    techSheet: {},
  },
  Fiore: {
    varietal: 'Barbera D\'Asti',
    grapes: ['Barbera'],
    vintage: 2016,
    appellation: 'Asti, Italy',
    tastingNotes: [
      'Dark cherry',
      'Red plum',
      'Anise',
      'Cinnamon',
    ],
    type: 'red',
    techSheet: {},
  },
  Sepp: {
    varietal: 'Zweigelt',
    grapes: ['Zweigelt'],
    vintage: 2015,
    appellation: 'Burgenland, Austria',
    tastingNotes: [
      'Red flowers',
      'Sour cherry',
      'White pepper',
      'Earthy',
    ],
    type: 'red',
    techSheet: {},
  },
  Brotte: {
    varietal: 'Grenache',
    grapes: ['Grenache', 'Syrah'],
    vintage: 2015,
    appellation: 'Chateauneuf-du-Pape, France',
    tastingNotes: [
      'Violets',
      'Black cherry',
      'Licorice',
      'Wild herbs',
    ],
    type: 'red',
    techSheet: {},
  },
  Masciarelli: {
    varietal: 'Montepulciano',
    grapes: ['Montepulciano'],
    vintage: 2015,
    appellation: 'Abruzzo, Italy',
    tastingNotes: [
      'Red currant',
      'Red cherry',
      'Smoky',
      'Award winning producer',
    ],
    type: 'red',
    techSheet: {},
  },
  Pecina: {
    varietal: 'Tempranillo',
    grapes: ['Tempranillo, 95%', 'Graciano, 5%'],
    vintage: 2015,
    appellation: 'Rioja, Spain',
    tastingNotes: [
      'Blackberry',
      'Scorched earth',
      'Dried tobacco',
      'Balsamic',
    ],
    type: 'red',
    techSheet: {},
  },
  Antioch: {
    varietal: 'Zinfandel',
    grapes: ['Zinfandel, 83%', 'Petit Sirah, 10%', 'Mataro, 6%', 'Carignan, 1%'],
    vintage: 2015,
    appellation: 'Contra Costa, California',
    tastingNotes: [
      'Ripe black cherry',
      'Sweet vanilla',
      'Dark chocolate',
      'Black raspberry',
    ],
    type: 'red',
    techSheet: {},
  },
  Espiritu: {
    varietal: 'Malbec',
    grapes: ['Malbec'],
    vintage: 2016,
    appellation: 'Mendoza, Argentina',
    tastingNotes: [
      'Purple flowers',
      'Black plums',
      'Dark chocolate',
      'Sappy fruit',
    ],
    type: 'red',
    techSheet: {},
  },
  Altamente: {
    varietal: 'Monastrell',
    grapes: ['Monastrell'],
    vintage: 2015,
    appellation: 'Jumilla, Spain',
    tastingNotes: [
      'Purple flowers',
      'Blackberry',
      'Boysenberry',
      'Tangy',
    ],
    type: 'red',
    techSheet: {},
  },
  Redwood: {
    varietal: 'Red Blend',
    grapes: ['Carignan', 'Valdigue', 'Syrah'],
    vintage: 2014,
    appellation: 'Mendocino, California',
    tastingNotes: [
      'Lilac',
      'Blackberry',
      'Kalamata olives',
      'Black tea',
    ],
    type: 'red',
    techSheet: {},
  },
  Peirano: {
    varietal: 'Merlot',
    grapes: ['Merlot'],
    vintage: 2014,
    appellation: 'Lodi, California',
    tastingNotes: [
      'Baking spices',
      'Boysenberry',
      'Musty',
      'Raspberry',
    ],
    type: 'red',
    techSheet: {},
  },
  Centenario: {
    varietal: 'Cabernet Sauvignon',
    grapes: ['Cabernet Sauvignon, 90%', 'Merlot, 5%', 'Carmenere, 5%'],
    vintage: 2015,
    appellation: 'Colchagua Valley, Chile',
    tastingNotes: [
      'Red cherry',
      'Sweet spice',
      'Chocolate',
      'Ripe tannins'
    ],
    type: 'red',
    techSheet: {}
  },
};

export default WineList;
