const WineList = {
  Neirano: {
    varietal: 'Prosecco',
    grapes: ['Glera'],
    vintage: 'NV',
    appellation: 'Veneto, Italy',
    tastingNotes: [],
    type: 'bubbly',
    techSheet: {},
  },
  Valor: {
    varietal: 'Cava',
    grapes: ['Xarel-lo', 'Macabeo', 'Parellada'],
    vintage: 'NV',
    appellation: 'Penedes, Spain',
    tastingNotes: [],
    type: 'bubbly',
    techSheet: {},
  },
  Mercat: {
    varietal: 'Sparkling Rose',
    grapes: ['Xarel-lo', 'Macabeo,', 'Parellada', 'Monastrell, 5%'],
    vintage: 'NV',
    appellation: 'Penedes, Spain',
    tastingNotes: [],
    type: 'bubbly',
    techSheet: {},
  },
  CaDelSarto: {
    varietal: 'Pinot Grigio',
    grapes: ['Pinot Grigio'],
    vintage: 2016,
    appellation: 'Friuli, Italy',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Fruitire: {
    varietal: 'Melon',
    grapes: ['Melon de Bourgogne', 'Chardonnay', 'Sauvignon Blanc'],
    vintage: 2016,
    appellation: 'Loire Valley, France',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Oniric: {
    varietal: 'Xarel-lo',
    grapes: ['Xarel-lo'],
    vintage: 2016,
    appellation: 'Rias Baixas, Spain',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  LastAugust: {
    varietal: 'Sauvignon Blanc',
    grapes: ['Sauvignon Blanc'],
    vintage: 2016,
    appellation: 'Lake County, California',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Terra: {
    varietal: 'Vermentino, Chardonnay',
    grapes: ['Vermentino, 60%', 'Chardonnay, 40%'],
    vintage: 2016,
    appellation: 'Corsica, France',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  } ,
  Perfekt: {
    varietal: 'Riesling',
    grapes: ['Riesling'],
    vintage: 2015,
    appellation: 'Mosel, Germany',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Scarpetta: {
    varietal: 'Friulano-Chardonnay',
    grapes: ['Chardonnay, 80%', 'Friulano, 20%'],
    vintage: 2015,
    appellation: 'Italy',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Frame: {
    varietal: 'Chardonnay',
    grapes: ['Chardonnay'],
    vintage: 2016,
    appellation: 'California',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Curator: {
    varietal: 'Chenin Blanc',
    grapes: ['Chenin Blanc, 60%', 'Chardonnay, 20%', 'Viognier, 20%'],
    vintage: 2016,
    appellation: 'South Africa',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  Hollys: {
    varietal: 'Chardonnay',
    grapes: ['Chardonnay'],
    vintage: 2016,
    appellation: 'California',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  CaDelRe: {
    varietal: 'Moscato D\'Asti',
    grapes: ['Moscato'],
    vintage: 2016,
    appellation: 'Asti, Italy',
    tastingNotes: [],
    type: 'white',
    techSheet: {},
  },
  LExcellence: {
    varietal: 'rose',
    grapes: ['Grenache, 40%', 'Cinsault, 40%', 'Syrah, 20%'],
    vintage: 2016,
    appellation: 'St. Chinian, France',
    tastingNotes: [],
    type: 'rose',
    techSheet: {},
  },
  Stagedive: {
    varietal: 'Pinot Noir',
    grapes: ['Pinot Noir'],
    vintage: 2016,
    appellation: 'California',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Fiore: {
    varietal: 'Barbera D\'Asti',
    grapes: ['Barbera'],
    vintage: 2016,
    appellation: 'Asti, Italy',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Sepp: {
    varietal: 'Zweigelt',
    grapes: ['Zweigelt'],
    vintage: 2015,
    appellation: 'Burgenland, Austria',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Brotte: {
    varietal: 'Grenache',
    grapes: ['Grenache', 'Syrah'],
    vintage: 2015,
    appellation: 'Chateauneuf-du-Pape, France',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Masciarelli: {
    varietal: 'Montepulciano',
    grapes: ['Montepulciano'],
    vintage: 2015,
    appellation: 'Abruzzo, Italy',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Pecina: {
    varietal: 'Tempranillo',
    grapes: ['Tempranillo, 95%', 'Graciano, 5%'],
    vintage: 2015,
    appellation: 'Rioja, Spain',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Antioch: {
    varietal: 'Zinfandel',
    grapes: ['Zinfandel, 83%', 'Petit Sirah, 10%', 'Mataro, 6%', 'Carignan, 1%'],
    vintage: 2015,
    appellation: 'Contra Costa, California',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Espiritu: {
    varietal: 'Malbec',
    grapes: ['Malbec'],
    vintage: 2016,
    appellation: 'Mendoza, Argentina',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Altamente: {
    varietal: 'Monastrell',
    grapes: ['Monastrell'],
    vintage: 2015,
    appellation: 'Jumilla, Spain',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Redwood: {
    varietal: 'Red Blend',
    grapes: ['Carignan', 'Valdigue', 'Syrah'],
    vintage: 2014,
    appellation: 'Mendocino, California',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Peirano: {
    varietal: 'Merlot',
    grapes: ['Merlot'],
    vintage: 2014,
    appellation: 'Lodi, California',
    tastingNotes: [],
    type: 'red',
    techSheet: {},
  },
  Centenario: {
    varietal: 'Cabernet Sauvignon',
    grapes: ['Cabernet Sauvignon, 90%', 'Merlot, 5%', 'Carmenere, 5%'],
    vintage: 2015,
    appellation: 'Colchagua Valley, Chile',
    tastingNotes: [],
    type: 'red',
    techSheet: {}
  },
};

export default WineList;
